[package]
name = "rusty-clock"
version = "0.1.0"
authors = ["Guillaume Pinot <texitoi@texitoi.eu>"]

[dependencies]
stm32f103xx-hal = { git = "https://github.com/ilya-epifanov/stm32f103xx-hal", rev = "3a8d64d3605b5eac9fd15eea0ba25319fbb8375c" }
stm32f103xx = { version = "0.10", features = ["rt"] }
cortex-m = "0.5"
cortex-m-rt = { version = "0.6", features = ["device"] }
cortex-m-rtfm = { git = "https://github.com/ykomatsu/cortex-m-rtfm", branch = "update" }
panic-semihosting = "0.5"
bme280 = "0.1.1"
stm32f103xx-rtc = { git = "https://github.com/TeXitoi/stm32f103xx-rtc", branch = "master" }
heapless = "0.3.6"
pwm-speaker = { git = "https://github.com/TeXitoi/pwm-speaker" }
il3820 = { git = "https://github.com/TeXitoi/il3820" }
embedded-hal = "0.2.1"
embedded-graphics = "0.4"

[patch.crates-io]
embedded-graphics = { git = "https://github.com/TeXitoi/embedded-graphics", branch = "font-refactor" }

[profile.dev]
opt-level = 1
lto = true
incremental = false

[profile.release]
lto = true
incremental = false
opt-level = "z"
debug = true
