[package]
name = "rusty-clock"
version = "0.1.0"
authors = ["Guillaume Pinot <texitoi@texitoi.eu>"]

[workspace]

[dependencies]
stm32f103xx-hal = { git = "https://github.com/japaric/stm32f103xx-hal", branch = "master" }
stm32f103xx = { version = "0.10", features = ["rt"] }
cortex-m = "0.5"
cortex-m-rt = { version = "0.6", features = ["device"] }
cortex-m-rtfm = { git = "https://github.com/ykomatsu/cortex-m-rtfm", branch = "update" }
panic-semihosting = "0.5"
bme280 = "0.1.1"
stm32f103xx-rtc = { git = "https://github.com/TeXitoi/stm32f103xx-rtc", branch = "master" }
heapless = "0.3.6"
pwm-speaker = { git = "https://github.com/TeXitoi/pwm-speaker" }
il3820 = { git = "https://github.com/TeXitoi/il3820" }
embedded-hal = "0.2.1"
embedded-graphics = "0.4.1"
portable = { path = "portable" }

[profile.dev]
opt-level = 1
lto = true
incremental = false

[profile.release]
lto = true
incremental = false
opt-level = "z"
debug = true
